# Generated by Django 2.2.10 on 2020-02-27 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_auto_20200226_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='short_name',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_registration.Role', to_field='short_name'),
        ),
    ]
